# Generated by Django 4.2 on 2026-01-23

from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='drt',
            field=models.CharField(blank=True, help_text='Apenas números', max_length=20, null=True, validators=[RegexValidator(message='DRT/Matrícula deve conter apenas números', regex='^\\d+$')], verbose_name='DRT/Matrícula'),
        ),
    ]
