# Generated by Django 4.2 on 2026-01-23

from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_drt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='endereco',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=9, validators=[RegexValidator(message='CEP deve estar no formato: 00000-000', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logradouro',
            field=models.CharField(blank=True, help_text='Rua, Avenida, etc.', max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, help_text='Apto, Sala, Bloco, etc.', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, max_length=2, validators=[RegexValidator(message='Estado deve ser a sigla com 2 letras maiúsculas (ex: SP)', regex='^[A-Z]{2}$')], verbose_name='Estado'),
        ),
    ]
