# Generated by Django 4.2 on 2026-01-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cirurgia_exame_servicomedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirurgia',
            name='tipo_cirurgia',
            field=models.CharField(
                choices=[('CMA', 'Cirurgias Maiores (CMA)'), ('cma', 'Cirurgias menores (cma)')],
                default='CMA',
                max_length=20,
                verbose_name='Tipo de Cirurgia'
            ),
        ),
    ]
