# Generated by Django 4.2.28 on 2026-02-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_servicomedico_codigo_sigtap_and_more"),
        ("core", "0006_merge_20260123_1615"),
    ]

    operations = []
