# Generated by Django 4.2.28 on 2026-02-18 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_merge_20260218_1127"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProducaoMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes_ano", models.DateField(verbose_name="Mês/Ano de Referência")),
                (
                    "especialidade",
                    models.CharField(max_length=255, verbose_name="Especialidade"),
                ),
                (
                    "vagas_ofertadas",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Vagas Ofertadas"
                    ),
                ),
                (
                    "total_agendamentos",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total de Agendamentos"
                    ),
                ),
                (
                    "perc_agendamentos",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="% Agendamentos",
                    ),
                ),
                (
                    "agendamentos_cota",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Agendamentos da Cota"
                    ),
                ),
                (
                    "perc_cota",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="% da Cota",
                    ),
                ),
                (
                    "vagas_bolsao",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Vagas de Bolsão"
                    ),
                ),
                (
                    "perc_bolsao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="% de Bolsão",
                    ),
                ),
                (
                    "vagas_nao_distribuidas",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Vagas Não Distribuídas"
                    ),
                ),
                (
                    "perc_nao_distribuidas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="% Não Distribuídas",
                    ),
                ),
                (
                    "vagas_extras",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Vagas Extras"
                    ),
                ),
                (
                    "perc_extras",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="% Extras",
                    ),
                ),
                (
                    "perc_desperdicadas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="% Desperdiçadas",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Importado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "importado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="producoes_importadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Importado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produção Mensal",
                "verbose_name_plural": "Produções Mensais",
                "ordering": ["-mes_ano", "especialidade"],
                "unique_together": {("mes_ano", "especialidade")},
            },
        ),
    ]
