# Generated by Django 4.2.30 on 2026-06-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_producao_mensal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='cadastrado_por',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
