# Generated by Django 4.2.30 on 2026-06-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_medico_cadastrado_por_delete_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Email Verificado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mudar_senha',
            field=models.BooleanField(default=False, verbose_name='Forçar Troca de Senha'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='registro_profissional',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Conselho'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_profissional',
            field=models.CharField(blank=True, choices=[('MED', 'Médico'), ('ENF', 'Enfermeiro'), ('NUT', 'Nutricionista'), ('FAR', 'Farmacêutico')], max_length=3, null=True, verbose_name='Tipo Profissional'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_registro',
            field=models.CharField(blank=True, choices=[('CRM', 'CRM'), ('COREN', 'COREN'), ('CRN', 'CRN'), ('CRF', 'CRF')], max_length=10, null=True, verbose_name='Conselho (Ex: CRM)'),
        ),
    ]
