# Generated by Django 5.2.14 on 2026-05-11 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=300, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$', 'Formato: 00.000.000/0000-00')], verbose_name='CNPJ')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50, verbose_name='Inscrição Municipal')),
                ('inscricao_estadual', models.CharField(blank=True, default='ISENTO', max_length=50, verbose_name='Inscrição Estadual')),
                ('logradouro', models.CharField(max_length=300, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=150, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=150, verbose_name='Cidade')),
                ('estado', models.CharField(default='SP', max_length=2, verbose_name='Estado (UF)')),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'Formato: 00000-000')], verbose_name='CEP')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('nome_representante', models.CharField(max_length=200, verbose_name='Nome do Representante Legal')),
                ('cpf_representante', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'Formato: 000.000.000-00')], verbose_name='CPF do Representante')),
                ('crm_representante', models.CharField(max_length=30, verbose_name='CRM do Representante')),
                ('nome_testemunha', models.CharField(max_length=200, verbose_name='Nome da Testemunha')),
                ('telefone_testemunha', models.CharField(max_length=20, verbose_name='Telefone da Testemunha')),
                ('email_testemunha', models.EmailField(max_length=254, verbose_name='E-mail da Testemunha')),
                ('data_inicio_contrato', models.DateField(verbose_name='Início da Vigência')),
                ('data_fim_contrato', models.DateField(verbose_name='Fim da Vigência')),
                ('numero_processo', models.CharField(blank=True, max_length=50, verbose_name='Número do Processo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('especialidades', models.ManyToManyField(related_name='prestadores', to='cadastro.especialidade', verbose_name='Especialidades Médicas')),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
                'ordering': ['nome_empresa'],
            },
        ),
        migrations.CreateModel(
            name='ServicoContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('consulta', 'Consulta Ambulatorial'), ('cirurgia_pequeno', 'Cirurgia de Pequeno Porte'), ('cirurgia_medio', 'Cirurgia de Médio Porte'), ('exame', 'Exame / Laudo'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de Serviço')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição do Serviço')),
                ('unidade_medida', models.CharField(default='Consulta', max_length=50, verbose_name='Unidade de Medida')),
                ('quantidade_estimada_mes', models.PositiveIntegerField(verbose_name='Qtde. Estimada/Mês')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário (R$)')),
                ('prazo_entrega_laudo_dias', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Prazo de Entrega do Laudo (dias úteis)')),
                ('remoto', models.BooleanField(default=False, verbose_name='Realizado Remotamente?')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.especialidade', verbose_name='Especialidade')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='cadastro.prestador')),
            ],
            options={
                'verbose_name': 'Serviço Contratado',
                'verbose_name_plural': 'Serviços Contratados',
                'ordering': ['tipo_servico', 'descricao'],
            },
        ),
    ]
