# Generated by Django 5.2.14 on 2026-05-11 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='contratos_pdf/%Y/%m/', verbose_name='Arquivo PDF')),
                ('nome_arquivo', models.CharField(editable=False, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('razao_social_extraida', models.CharField(blank=True, max_length=300, verbose_name='Razão Social (extraída)')),
                ('cnpj_extraido', models.CharField(blank=True, max_length=18, verbose_name='CNPJ (extraído)')),
                ('objeto_extraido', models.TextField(blank=True, verbose_name='Objeto do Contrato (extraído)')),
                ('servicos_extraidos', models.JSONField(blank=True, default=list, verbose_name='Serviços (extraídos)')),
                ('especialidade_extraida', models.CharField(blank=True, max_length=200, verbose_name='Especialidade (extraída)')),
                ('data_inicio_extraida', models.DateField(blank=True, null=True, verbose_name='Data de Início (extraída)')),
                ('data_fim_extraida', models.DateField(blank=True, null=True, verbose_name='Data Fim (extraída)')),
                ('meses_vigencia_extraidos', models.PositiveSmallIntegerField(default=0, verbose_name='Meses de Vigência')),
                ('valor_mensal_extraido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Mensal (extraído)')),
                ('valor_global_extraido', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Global (extraído)')),
                ('numero_processo_extraido', models.CharField(blank=True, max_length=50, verbose_name='Nº do Processo (extraído)')),
                ('erro_extracao', models.TextField(blank=True, verbose_name='Erro de Extração')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de revisão'), ('confirmado', 'Confirmado e cadastrado'), ('erro', 'Erro na extração'), ('ignorado', 'Ignorado')], default='pendente', max_length=20, verbose_name='Status')),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_importados', to='cadastro.prestador', verbose_name='Prestador vinculado')),
            ],
            options={
                'verbose_name': 'Contrato Importado',
                'verbose_name_plural': 'Contratos Importados',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
