# Generated by Django 5.2.14 on 2026-05-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_campos_opcionais_prestador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='prestadores', to='cadastro.especialidade', verbose_name='Especialidades Médicas'),
        ),
        migrations.AlterField(
            model_name='servicocontratado',
            name='unidade_medida',
            field=models.CharField(blank=True, default='Consulta', max_length=50, verbose_name='Unidade de Medida'),
        ),
    ]
