# Generated manually
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_campos_opcionais_prestador'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='producao_xls/%Y/%m/', verbose_name='Arquivo XLS')),
                ('nome_arquivo', models.CharField(editable=False, max_length=255)),
                ('tipo', models.CharField(
                    choices=[('consulta', 'Consultas'), ('cirurgia_exame', 'Cirurgias / Exames')],
                    default='consulta', max_length=20, verbose_name='Tipo de Relatório')),
                ('data_inicio_periodo', models.DateField(blank=True, null=True, verbose_name='Início do Período')),
                ('data_fim_periodo', models.DateField(blank=True, null=True, verbose_name='Fim do Período')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(
                    choices=[
                        ('pendente', 'Pendente de revisão'),
                        ('confirmado', 'Confirmado e cadastrado'),
                        ('erro', 'Erro na extração'),
                        ('ignorado', 'Ignorado'),
                    ],
                    default='pendente', max_length=20, verbose_name='Status')),
                ('erro_processamento', models.TextField(blank=True, verbose_name='Erro de Processamento')),
                ('total_agendas', models.PositiveIntegerField(default=0, verbose_name='Total de Agendas')),
                ('total_medicos', models.PositiveIntegerField(default=0, verbose_name='Total de Registros de Médicos')),
            ],
            options={
                'verbose_name': 'Upload de Produção',
                'verbose_name_plural': 'Uploads de Produção',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProducaoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='cadastro.uploadproducao')),
                ('nome_agenda', models.CharField(max_length=200, verbose_name='Nome da Agenda')),
                ('vagas_ofertadas', models.IntegerField(default=0)),
                ('agend_totais', models.IntegerField(default=0)),
                ('agend_totais_pct', models.FloatField(default=0)),
                ('agend_bolsao', models.IntegerField(default=0)),
                ('agend_bolsao_pct', models.FloatField(default=0)),
                ('nao_distribuidas', models.IntegerField(default=0)),
                ('nao_distribuidas_pct', models.FloatField(default=0)),
                ('cota', models.IntegerField(default=0)),
                ('cota_pct', models.FloatField(default=0)),
                ('extra', models.IntegerField(default=0)),
                ('extra_pct', models.FloatField(default=0)),
                ('total_geral', models.IntegerField(default=0)),
                ('presencial', models.IntegerField(default=0)),
                ('presencial_pct', models.FloatField(default=0)),
                ('teleconsulta', models.IntegerField(default=0)),
                ('teleconsulta_pct', models.FloatField(default=0)),
                ('agend_totais_2', models.IntegerField(default=0)),
                ('agend_totais_2_pct', models.FloatField(default=0)),
                ('recepcao_ausente', models.IntegerField(default=0)),
                ('recepcao_ausente_pct', models.FloatField(default=0)),
                ('recepcao_dispensado', models.IntegerField(default=0)),
                ('recepcao_dispensado_pct', models.FloatField(default=0)),
                ('recepcao_desistente', models.IntegerField(default=0)),
                ('recepcao_desistente_pct', models.FloatField(default=0)),
                ('recepcao_nao_informado', models.IntegerField(default=0)),
                ('recepcao_nao_informado_pct', models.FloatField(default=0)),
                ('alta', models.IntegerField(default=0)),
                ('alta_pct', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Produção por Agenda',
                'verbose_name_plural': 'Produções por Agenda',
                'ordering': ['nome_agenda'],
                'unique_together': {('upload', 'nome_agenda')},
            },
        ),
        migrations.CreateModel(
            name='ProducaoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='cadastro.producaoagenda')),
                ('nome_medico', models.CharField(max_length=200, verbose_name='Nome do Médico')),
                ('vagas_ofertadas', models.IntegerField(default=0)),
                ('agend_totais', models.IntegerField(default=0)),
                ('agend_totais_pct', models.FloatField(default=0)),
                ('agend_bolsao', models.IntegerField(default=0)),
                ('agend_bolsao_pct', models.FloatField(default=0)),
                ('nao_distribuidas', models.IntegerField(default=0)),
                ('nao_distribuidas_pct', models.FloatField(default=0)),
                ('cota', models.IntegerField(default=0)),
                ('cota_pct', models.FloatField(default=0)),
                ('extra', models.IntegerField(default=0)),
                ('extra_pct', models.FloatField(default=0)),
                ('total_geral', models.IntegerField(default=0)),
                ('presencial', models.IntegerField(default=0)),
                ('presencial_pct', models.FloatField(default=0)),
                ('teleconsulta', models.IntegerField(default=0)),
                ('teleconsulta_pct', models.FloatField(default=0)),
                ('agend_totais_2', models.IntegerField(default=0)),
                ('agend_totais_2_pct', models.FloatField(default=0)),
                ('recepcao_ausente', models.IntegerField(default=0)),
                ('recepcao_ausente_pct', models.FloatField(default=0)),
                ('recepcao_dispensado', models.IntegerField(default=0)),
                ('recepcao_dispensado_pct', models.FloatField(default=0)),
                ('recepcao_desistente', models.IntegerField(default=0)),
                ('recepcao_desistente_pct', models.FloatField(default=0)),
                ('recepcao_nao_informado', models.IntegerField(default=0)),
                ('recepcao_nao_informado_pct', models.FloatField(default=0)),
                ('alta', models.IntegerField(default=0)),
                ('alta_pct', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Produção por Médico',
                'verbose_name_plural': 'Produções por Médico',
                'ordering': ['nome_medico'],
            },
        ),
    ]
