# Generated by Django 5.2.14 on 2026-05-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_prestador_especialidades_and_more'),
        ('cadastro', '0004_producao_siresp'),
    ]

    operations = [
    ]
