# Generated by Django 5.2.14 on 2026-05-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_medico'),
        ('cadastro', '0005_merge_20260512_1804'),
    ]

    operations = [
    ]
