# Generated by Django 5.2.14 on 2026-05-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_agendamapeamento'),
        ('cadastro', '0006_merge_0005_medico_0005_merge_20260512_1804'),
    ]

    operations = [
    ]
