# Generated by Django 5.2.14 on 2026-05-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_merge_20260513_1503'),
        ('cadastro', '0007_seed_especialidades'),
    ]

    operations = [
    ]
