# Generated by Django 5.2.14 on 2026-05-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_limpar_formatacao_campos'),
        ('cadastro', '0008_merge_20260513_1519'),
    ]

    operations = [
    ]
