# Generated by Django 5.2.14 on 2026-05-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_aumenta_maxlength_campos_digitos'),
        ('cadastro', '0009_merge_20260513_1534'),
    ]

    operations = [
    ]
