# Generated by Django 4.2.30 on 2026-06-10 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_merge_20260513_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cep',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(\\d{8})?$', 'Informe os 8 dígitos do CEP')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{11})?$', 'Informe os 11 dígitos do CPF')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='cep',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(\\d{8})?$', 'Informe os 8 dígitos do CEP')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'Informe os 14 dígitos do CNPJ sem pontuação')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='cpf_representante',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(\\d{11})?$', 'Informe os 11 dígitos do CPF')], verbose_name='CPF do Representante'),
        ),
    ]
